### PR TITLE
Stop subscriptions

### LINKED ISSUE #4: Need a way to stop subscriptions with an action when a component is destroyed
There is already some logic to stop subscriptions in the middleware, but only if a subscription action is dispatched that has been previously dispatched, presumably to keep things idempotent and support re-subscribing with new arguments.

There is also the scenario where you want to stop a subscription to avoid over-fetching after your app transitions to a new state, thus the motivation for previous patterns like [template level subscriptions](https://www.discovermeteor.com/blog/template-level-subscriptions/).

I have been playing around with how to do this in an elegant way, but I still haven't come up with something that feels right.

### PR DESCRIPTION
**Pull request by Koleok**
Closes #4

### CODE REVIEW

**Comment by Koleok** [comment]
@samybob1 Just saw that you mentioned updating the `README` in #4 , I actually updated it in this PR but give it a second set of eyes to see if i missed anything 😄

**Comment by Koleok** [comment]
@samybob1  Any thoughts so far?

**Comment by Koleok** [comment]
I also am putting together [this little ditty](https://github.com/remedux/subscription-container) as a practical use case

**Comment by samybob1** [comment]
Hi @Koleok. This is perfect, I'm on it.

**Comment by samybob1** [comment]
@Koleok Now I'll merge the demo, then I'll publish everything :wink:

**Comment by samybob1** [comment]
@Koleok Done, let me know if something is wrong. :stuck_out_tongue: Thank you again for all your work!

**Comment by Koleok** [comment]
Thanks @samybob1! This I am so excited to have these two tools starting to cooperate 😄

**Pull request merged**
